package com.bindothorpe.champions.domain.skill;

public enum SkillId {
    TEST_SKILL(), TEST_SKILL_2, KITING_ARROW, BOUNCING_ARROW, EXPLOSION, ASSASSIN_PASSIVE, ICE_PRISON, HUNTERS_HEART, EXPLOSIVE_BOMB, HEAD_BUTT, RALLY;
}
