name: Champions
version: '${project.version}'
main: com.bindothorpe.champions.ChampionsPlugin
api-version: 1.19
depend: [ProtocolLib]
commands:
  build:
    usage: /build
  team:
    usage: /team <team color>
  skills:
    usage: /skills
  game:
    usage: /game
  shop:
    usage: /shop
