name: Champions
version: '${project.version}'
main: com.bindothorpe.champions.ChampionsPlugin
api-version: 1.19
commands:
  build:
    usage: /build
  team:
    usage: /team <team color>
  game:
    usage: /game
  shop:
    usage: /shop
  cp:
    usage: /cp
  map:
    usage: /map
  sound:
    usage: /sound <sound> <volume> <pitch>
