package com.bindothorpe.champions.domain.customItem;

public enum CustomItemId {
    SERRATED_DIRK, DUSK_BLADE, PHAGE, MYSTICAL_SEED, ELDER_LEAF, SPIRIT_FEATHER, HEARTWOOD_CUIRASS, SPELLBLADE, TITANS_GRASP, BOXING_GLOVE, LONG_SWORD
}
